apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaccional-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: transaccional
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: transaccional
  template:
    metadata:
      labels:
        app: transaccional
    spec:
      volumes:
      - name: nfs-sa-in
        persistentVolumeClaim:
          claimName: nfs-sa-in-claim
      - name: nfs-sa-out
        persistentVolumeClaim:
          claimName: nfs-sa-out-claim
      - name: nfs-procesos
        persistentVolumeClaim:
          claimName: nfs-procesos-claim
      - name: nfs-cesantias
        persistentVolumeClaim:
          claimName: nfs-cesantias-claim
      - name: local-logs
        persistentVolumeClaim:
          claimName: local-host-logs-claim
      containers:
      - name : transaccional
        image: harbor.da.arus.com.co/arus/transaccional:{{ .Values.image.tag }}
        imagePullPolicy: Always
        env:
        - name: JAVA_OPTS
          value: >
            -Xms3072m -Xmx3072m -XX:NewSize=512m -XX:MaxNewSize=512m -XX:PermSize=1024m -XX:MaxPermSize=1024m 
            -DnamefileLog=/mnt/logs/transaccional/transaccional.log -DmaxLogFileSize=512MB -DmaxLogBackupSize=9 
            -Dorg.jboss.resolver.warning=true -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 
            -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:+CMSParallelRemarkEnabled 
            -Dfile.encoding=ISO-8859-1 -Duser.region=CO -Duser.language=es -Duser.country=CO -Duser.timezone=America/Bogota 
            -Doc4j.userThreads=true -Dstandalone  -Djava.security.egd=file:/dev/./urandom -Dsecurerandom.source=file:/dev/./urandom 
            -DcerrarTransacciones="1" -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.local.only=false 
            -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false 
            -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.rmi.port=9998 -XX:+HeapDumpOnOutOfMemoryError 
            -XX:HeapDumpPath=/mnt/logs/transaccional -Ddomain=suaporte.com.co -Dhome.sso=https://www.suaporte.com.co/sso/#/ 
            -Dauth.sso=https://www.suaporte.com.co/auth
        envFrom:
        - configMapRef:
            name: general-config
        - secretRef:  
            name: transaccional-secret         
        ports:
        - containerPort: 8443
          hostPort: 8443
          name: 80tcp8443
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 1Gi         
        volumeMounts:
        - mountPath: /sa_in
          name: nfs-sa-in
        - mountPath: /procesos
          name: nfs-procesos
        - mountPath: /sa_out
          name: nfs-sa-out
        - mountPath: /cesantias
          name: nfs-cesantias
        - mountPath: /mnt/logs
          name: local-logs
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
            - SYS_RESOURCE  
      imagePullSecrets:
        - name: regcred
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: group
                operator: In
                values:
                - {{ .Values.node.tag }}
              - key: env
                operator: In
                values:
                - {{ .Values.node.env }}        
        podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ .Values.node.tag }}
              topologyKey: kubernetes.io/hostname
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0

