# Default values for transaccional.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#namespace: appsarus
image:
  tag: lab
node:
  tag: transaccional
  env: lab

replicaCount: 1

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
