apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-frontend-service
#  namespace: appsarus
  labels:
    app: {{ .Chart.Name }}-frontend-service
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  ports:
  - name: webui
    port: 80
    targetPort: 80
  selector:
    app: {{ .Chart.Name }}-frontend