apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-backend-service
#  namespace: appsarus
  labels:
    app: {{ .Chart.Name }}-backend-service
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  ports:
  - name: webui
    port: 8090
    targetPort: 8090
  selector:
    app: {{ .Chart.Name }}-backend